export type Product = {
  id: string;
  name: string;
  brand: string;
  category: string;
  price: number;
  subscribePrice: number;
  rating: number;
  reviews: number;
  badge?: "Best Seller" | "New" | "Lab Verified" | "Bundle Deal" | "RUO";
  description: string;
  keyIngredients: string[];
  servings: number;
  inStock: boolean;
  emoji: string;
};

export const products: Product[] = [
  // General Wellness
  {
    id: "omega-3",
    name: "Ultra-Pure Omega-3 Fish Oil",
    brand: "Supplement Shack",
    category: "general-wellness",
    price: 34.99,
    subscribePrice: 29.74,
    rating: 4.8,
    reviews: 412,
    badge: "Best Seller",
    description: "Molecularly distilled triglyceride-form omega-3 with 1,200mg EPA + DHA per serving. IFOS 5-star certified.",
    keyIngredients: ["EPA 720mg", "DHA 480mg", "Vitamin E (antioxidant)"],
    servings: 90,
    inStock: true,
    emoji: "🐟",
  },
  {
    id: "vitamin-d3-k2",
    name: "Vitamin D3 + K2 MK-7",
    brand: "Supplement Shack",
    category: "general-wellness",
    price: 24.99,
    subscribePrice: 21.24,
    rating: 4.9,
    reviews: 287,
    badge: "Lab Verified",
    description: "5,000 IU D3 paired with 100mcg MK-7 K2 for superior calcium metabolism and immune support.",
    keyIngredients: ["Vitamin D3 5,000 IU", "Vitamin K2 MK-7 100mcg"],
    servings: 120,
    inStock: true,
    emoji: "☀️",
  },
  {
    id: "magnesium-glycinate",
    name: "Magnesium Glycinate 400mg",
    brand: "Supplement Shack",
    category: "general-wellness",
    price: 29.99,
    subscribePrice: 25.49,
    rating: 4.7,
    reviews: 341,
    badge: "Best Seller",
    description: "Highly bioavailable chelated magnesium for sleep quality, muscle relaxation, and stress reduction.",
    keyIngredients: ["Magnesium Glycinate 400mg", "Elemental Magnesium 200mg"],
    servings: 90,
    inStock: true,
    emoji: "💤",
  },
  {
    id: "probiotic-50b",
    name: "Advanced Probiotic 50 Billion CFU",
    brand: "Supplement Shack",
    category: "general-wellness",
    price: 44.99,
    subscribePrice: 38.24,
    rating: 4.6,
    reviews: 198,
    badge: "New",
    description: "15 clinically studied strains with prebiotic fiber support. Acid-resistant delayed-release capsule.",
    keyIngredients: ["L. acidophilus", "B. longum", "L. rhamnosus", "Prebiotic FOS"],
    servings: 30,
    inStock: true,
    emoji: "🦠",
  },
  {
    id: "zinc-copper",
    name: "Zinc + Copper Balance",
    brand: "Supplement Shack",
    category: "general-wellness",
    price: 18.99,
    subscribePrice: 16.14,
    rating: 4.5,
    reviews: 142,
    description: "Optimal 15:1 zinc-to-copper ratio for immune function, testosterone support, and enzyme activity.",
    keyIngredients: ["Zinc Bisglycinate 30mg", "Copper 2mg"],
    servings: 60,
    inStock: true,
    emoji: "🛡️",
  },

  // Sports Nutrition
  {
    id: "whey-isolate",
    name: "CFM Whey Protein Isolate",
    brand: "Supplement Shack",
    category: "sports-nutrition",
    price: 64.99,
    subscribePrice: 55.24,
    rating: 4.9,
    reviews: 892,
    badge: "Best Seller",
    description: "Cold-filtered microfiltration whey isolate. 27g protein per scoop, <1g fat, <1g carbs. Instantized for zero clumping.",
    keyIngredients: ["Whey Protein Isolate 27g", "BCAA 6.5g", "Leucine 2.8g"],
    servings: 30,
    inStock: true,
    emoji: "💪",
  },
  {
    id: "creatine-mono",
    name: "Creatine Monohydrate 5g",
    brand: "Supplement Shack",
    category: "sports-nutrition",
    price: 29.99,
    subscribePrice: 25.49,
    rating: 5.0,
    reviews: 1204,
    badge: "Best Seller",
    description: "Creapure® certified creatine monohydrate — the most researched performance supplement in history.",
    keyIngredients: ["Creapure® Creatine Monohydrate 5g"],
    servings: 60,
    inStock: true,
    emoji: "⚡",
  },
  {
    id: "pre-workout",
    name: "Pre-Workout Elite",
    brand: "Supplement Shack",
    category: "sports-nutrition",
    price: 49.99,
    subscribePrice: 42.49,
    rating: 4.7,
    reviews: 543,
    badge: "Lab Verified",
    description: "Fully dosed pre-workout with clinical servings of each ingredient. No prop blends, no fillers.",
    keyIngredients: ["Citrulline Malate 8g", "Beta-Alanine 3.2g", "Caffeine 300mg", "Alpha-GPC 300mg"],
    servings: 30,
    inStock: true,
    emoji: "🚀",
  },
  {
    id: "bcaa-eaa",
    name: "EAA + BCAA Recovery Matrix",
    brand: "Supplement Shack",
    category: "sports-nutrition",
    price: 39.99,
    subscribePrice: 33.99,
    rating: 4.6,
    reviews: 321,
    description: "Full essential amino acid profile with electrolytes for intra-workout hydration and recovery.",
    keyIngredients: ["EAAs 10g", "BCAAs 5g (2:1:1)", "Coconut Water Powder 1g"],
    servings: 30,
    inStock: true,
    emoji: "🔄",
  },
  {
    id: "beta-alanine",
    name: "Beta-Alanine CarnoSyn®",
    brand: "Supplement Shack",
    category: "sports-nutrition",
    price: 22.99,
    subscribePrice: 19.54,
    rating: 4.5,
    reviews: 187,
    description: "Patented CarnoSyn® beta-alanine clinically shown to increase carnosine levels and delay fatigue.",
    keyIngredients: ["CarnoSyn® Beta-Alanine 3,200mg"],
    servings: 60,
    inStock: true,
    emoji: "🔥",
  },

  // Anti-Aging
  {
    id: "nmn-500",
    name: "NMN 500mg Stabilized",
    brand: "Supplement Shack",
    category: "anti-aging",
    price: 79.99,
    subscribePrice: 67.99,
    rating: 4.8,
    reviews: 267,
    badge: "Lab Verified",
    description: "Stabilized β-Nicotinamide Mononucleotide. Third-party purity verified ≥99%. Supports NAD+ biosynthesis and cellular energy.",
    keyIngredients: ["β-NMN 500mg", "BioPerine® 5mg (absorption)"],
    servings: 60,
    inStock: true,
    emoji: "🔋",
  },
  {
    id: "resveratrol-trans",
    name: "Trans-Resveratrol 500mg",
    brand: "Supplement Shack",
    category: "anti-aging",
    price: 54.99,
    subscribePrice: 46.74,
    rating: 4.7,
    reviews: 183,
    badge: "Best Seller",
    description: "Japanese Knotweed-derived 98%+ trans-resveratrol — the bioactive form studied for SIRT1 activation and longevity.",
    keyIngredients: ["Trans-Resveratrol 500mg", "Quercetin 250mg", "BioPerine® 10mg"],
    servings: 60,
    inStock: true,
    emoji: "🍇",
  },
  {
    id: "collagen-peptides",
    name: "Hydrolyzed Collagen Peptides",
    brand: "Supplement Shack",
    category: "anti-aging",
    price: 44.99,
    subscribePrice: 38.24,
    rating: 4.6,
    reviews: 412,
    description: "Grass-fed bovine type I & III collagen peptides. Unflavored, mixes clear in hot or cold liquids.",
    keyIngredients: ["Collagen Peptides 20g", "Vitamin C 90mg", "Hyaluronic Acid 80mg"],
    servings: 30,
    inStock: true,
    emoji: "✨",
  },
  {
    id: "coq10-ubiquinol",
    name: "CoQ10 Ubiquinol 200mg",
    brand: "Supplement Shack",
    category: "anti-aging",
    price: 49.99,
    subscribePrice: 42.49,
    rating: 4.8,
    reviews: 224,
    badge: "Lab Verified",
    description: "Active ubiquinol form of CoQ10 — superior absorption vs. ubiquinone. Essential for mitochondrial ATP production.",
    keyIngredients: ["Kaneka QH® Ubiquinol 200mg"],
    servings: 60,
    inStock: true,
    emoji: "⚗️",
  },
  {
    id: "astaxanthin",
    name: "Astaxanthin 12mg",
    brand: "Supplement Shack",
    category: "anti-aging",
    price: 34.99,
    subscribePrice: 29.74,
    rating: 4.9,
    reviews: 156,
    badge: "New",
    description: "AstaReal® microalgae-derived astaxanthin — one of nature's most powerful antioxidants for skin and eye health.",
    keyIngredients: ["AstaReal® Astaxanthin 12mg"],
    servings: 60,
    inStock: true,
    emoji: "🦐",
  },

  // Peptides (research-grade for topical/external use)
  {
    id: "bpc-157-topical",
    name: "BPC-157 Topical Complex",
    brand: "Supplement Shack",
    category: "peptides",
    price: 89.99,
    subscribePrice: 76.49,
    rating: 4.8,
    reviews: 134,
    badge: "Lab Verified",
    description: "Professional-grade BPC-157 peptide complex formulated as a topical preparation. Certificate of Analysis included.",
    keyIngredients: ["BPC-157 500mcg/mL", "DMSO Vehicle", "Copper Peptide GHK-Cu"],
    servings: 30,
    inStock: true,
    emoji: "🧬",
  },
  {
    id: "ghk-cu-serum",
    name: "GHK-Cu Copper Peptide Serum",
    brand: "Supplement Shack",
    category: "peptides",
    price: 74.99,
    subscribePrice: 63.74,
    rating: 4.7,
    reviews: 98,
    badge: "New",
    description: "1% GHK-Cu copper tripeptide serum for skin regeneration, collagen stimulation, and wound support.",
    keyIngredients: ["GHK-Cu 1% (1000mg/100mL)", "Hyaluronic Acid", "Niacinamide"],
    servings: 60,
    inStock: true,
    emoji: "💎",
  },
  {
    id: "tb500-topical",
    name: "TB-500 Fragment Topical",
    brand: "Supplement Shack",
    category: "peptides",
    price: 94.99,
    subscribePrice: 80.74,
    rating: 4.6,
    reviews: 67,
    badge: "Lab Verified",
    description: "Thymosin Beta-4 actin-binding fragment for topical application. HPLC-verified purity ≥98%.",
    keyIngredients: ["TB-500 Fragment 1mg/mL", "Sterile Vehicle"],
    servings: 30,
    inStock: true,
    emoji: "🔬",
  },

  // RUO Peptides
  {
    id: "bpc-157-ruo",
    name: "BPC-157 (Research Grade)",
    brand: "Supplement Shack",
    category: "peptides-ruo",
    price: 59.99,
    subscribePrice: 50.99,
    rating: 4.9,
    reviews: 89,
    badge: "RUO",
    description: "Body Protection Compound-157. Lyophilized powder, ≥99% purity by HPLC. For in vitro research use only.",
    keyIngredients: ["BPC-157 5mg lyophilized", "Argon gas sealed"],
    servings: 1,
    inStock: true,
    emoji: "🧪",
  },
  {
    id: "tb-500-ruo",
    name: "TB-500 / Thymosin Beta-4 (RUO)",
    brand: "Supplement Shack",
    category: "peptides-ruo",
    price: 74.99,
    subscribePrice: 63.74,
    rating: 4.8,
    reviews: 52,
    badge: "RUO",
    description: "Thymosin Beta-4 synthetic peptide. Lyophilized, 5mg vial. ≥98% purity. Research use only.",
    keyIngredients: ["TB-500 5mg lyophilized"],
    servings: 1,
    inStock: true,
    emoji: "🧪",
  },
  {
    id: "epithalon-ruo",
    name: "Epithalon Tetrapeptide (RUO)",
    brand: "Supplement Shack",
    category: "peptides-ruo",
    price: 49.99,
    subscribePrice: 42.49,
    rating: 4.7,
    reviews: 41,
    badge: "RUO",
    description: "Ala-Glu-Asp-Gly tetrapeptide, telomerase research standard. 10mg vial. ≥99% purity by MS.",
    keyIngredients: ["Epithalon 10mg lyophilized"],
    servings: 1,
    inStock: true,
    emoji: "🧪",
  },
  {
    id: "selank-ruo",
    name: "Selank Heptapeptide (RUO)",
    brand: "Supplement Shack",
    category: "peptides-ruo",
    price: 44.99,
    subscribePrice: 38.24,
    rating: 4.6,
    reviews: 38,
    badge: "RUO",
    description: "Tuftsin-derived anxiolytic peptide analog. 5mg research vial. For laboratory/in vitro research.",
    keyIngredients: ["Selank 5mg lyophilized"],
    servings: 1,
    inStock: true,
    emoji: "🧪",
  },
  {
    id: "cjc-1295-ruo",
    name: "CJC-1295 w/ DAC (RUO)",
    brand: "Supplement Shack",
    category: "peptides-ruo",
    price: 69.99,
    subscribePrice: 59.49,
    rating: 4.8,
    reviews: 62,
    badge: "RUO",
    description: "Growth hormone releasing hormone analog with Drug Affinity Complex. 2mg vial. ≥98% purity.",
    keyIngredients: ["CJC-1295 DAC 2mg lyophilized"],
    servings: 1,
    inStock: true,
    emoji: "🧪",
  },
  {
    id: "ipamorelin-ruo",
    name: "Ipamorelin (RUO)",
    brand: "Supplement Shack",
    category: "peptides-ruo",
    price: 54.99,
    subscribePrice: 46.74,
    rating: 4.7,
    reviews: 48,
    badge: "RUO",
    description: "Selective GHRP-2 analog. 5mg research vial. For in vitro research. ≥99% purity by HPLC/MS.",
    keyIngredients: ["Ipamorelin 5mg lyophilized"],
    servings: 1,
    inStock: true,
    emoji: "🧪",
  },

  // Wearables
  {
    id: "cgm-starter-kit",
    name: "CGM Starter Kit — 1 Month",
    brand: "Supplement Shack",
    category: "wearables",
    price: 89.99,
    subscribePrice: 76.49,
    rating: 4.7,
    reviews: 231,
    badge: "Best Seller",
    description: "Continuous glucose monitoring kit — 2 sensors included. Pairs with free app for real-time metabolic feedback.",
    keyIngredients: ["2× CGM Sensors (14-day each)", "App subscription 30 days"],
    servings: 60,
    inStock: true,
    emoji: "📈",
  },
  {
    id: "hrv-ring",
    name: "HRV & Sleep Tracking Ring",
    brand: "Supplement Shack",
    category: "wearables",
    price: 249.99,
    subscribePrice: 212.49,
    rating: 4.8,
    reviews: 183,
    badge: "New",
    description: "Medical-grade HRV, SpO2, sleep staging, and recovery scoring. 7-day battery. Titanium shell.",
    keyIngredients: ["HRV Monitor", "SpO2 Sensor", "Temperature Sensor", "PPG Sensor"],
    servings: 1,
    inStock: true,
    emoji: "💍",
  },
  {
    id: "bio-patch",
    name: "Metabolic Bio-Patch Kit",
    brand: "Supplement Shack",
    category: "wearables",
    price: 59.99,
    subscribePrice: 50.99,
    rating: 4.5,
    reviews: 97,
    badge: "New",
    description: "Sweat-based lactate and glucose bio-sensing patch with Bluetooth transmission. 5-patch kit.",
    keyIngredients: ["5× Bio-Sensing Patches", "Bluetooth Module"],
    servings: 5,
    inStock: true,
    emoji: "🩺",
  },
];

export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => p.category === category);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.badge === "Best Seller").slice(0, 4);
}
